[package]
name = "Multiplayer_FPS"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
r = { package = "rand", version = "0.8" }
macroquad = "0.3.24"